// SPDX-License-Identifier: MIT
pragma solidity ^0.8.35;

import {
    Nox,
    euint256,
    externalEuint256
} from "@iexec-nox/nox-protocol-contracts/contracts/sdk/Nox.sol";

/// @title ConfidentialStrategyVault
/// @notice Stores one encrypted bounty strategy for each wallet.
/// @dev The ciphertext handle is visible on-chain, but only the owner and this
/// contract receive permission to use or decrypt the represented value.
contract ConfidentialStrategyVault {
    struct Strategy {
        euint256 encryptedPlan;
        uint64 updatedAt;
    }

    mapping(address owner => Strategy strategy) private strategies;

    event StrategyUpdated(address indexed owner, uint64 updatedAt);

    /// @notice Save or replace the caller's encrypted strategy.
    /// @param encryptedPlan External Nox handle bound to this contract.
    /// @param handleProof Proof generated by the Nox JavaScript SDK.
    function setStrategy(
        externalEuint256 encryptedPlan,
        bytes calldata handleProof
    ) external {
        euint256 plan = Nox.fromExternal(encryptedPlan, handleProof);

        strategies[msg.sender] = Strategy({
            encryptedPlan: plan,
            updatedAt: uint64(block.timestamp)
        });

        // Every derived/stored handle needs explicit permissions in Nox.
        Nox.allowThis(plan);
        Nox.allow(plan, msg.sender);

        emit StrategyUpdated(msg.sender, uint64(block.timestamp));
    }

    /// @notice Return the opaque handle and public update time for an account.
    /// @dev Reading the handle does not grant permission to decrypt its value.
    function getStrategy(address owner)
        external
        view
        returns (bytes32 encryptedPlanHandle, uint64 updatedAt)
    {
        Strategy storage strategy = strategies[owner];
        return (euint256.unwrap(strategy.encryptedPlan), strategy.updatedAt);
    }
}
